### PR TITLE
Add a form GitHub issue template for proposals

### PR DESCRIPTION
**Pull request by Calinou**
Similar to https://github.com/godotengine/godot/pull/49364, but for the Godot proposals repository.

GitHub now supports forms as issue templates (currently in private beta). Godot has been opted into this private beta, which makes this new feature usable on the Godot proposals repository.

Inspired by the ImageMagick form:

https://github.com/ImageMagick/ImageMagick/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml

### CODE REVIEW

**Comment by LikeLakers2** [comment]
Perhaps this is a silly inquiry, but I notice that viewing the file in this PR doesn't provide a preview, unlike the ImageMagick one you linked which *does* provide a preview.

Is that just the result of it not being in master?

**Comment by Joakker** [comment]
@LikeLakers2 I suspect this happens when the branch is force pushed, since no files actually change. Clicking on the `Files Changed` tab does it for me

**Comment by LikeLakers2** [comment]
> @LikeLakers2 I suspect this happens when the branch is force pushed, since no files actually change. Clicking on the `Files Changed` tab does it for me

Oh no, not that preview. Go click on the link Calinou provided, and you'll see what sort of preview I mean -- the .yml file is rendered as a form rather than as its source text. What I was saying was that I can't seem to get that same sort of preview out of the file in this PR.

**Comment by pycbouh** [comment]
Hmm, interesting indeed. In the PR on the main repo preview works on the commit itself:
https://github.com/godotengine/godot/blob/9da1424ba2b76f0ed108dd07314ef96138a6e2ec/.github/ISSUE_TEMPLATE/bug_report.yml

image

But not here:
https://github.com/godotengine/godot-proposals/blob/c97a608d1f9c52c81c21c4abacc4d510f914faed/.github/ISSUE_TEMPLATE/feature_enhancement_proposal.yml

image

Maybe only the main repo was opted-in for this private beta?

**Comment by LikeLakers2** [comment]
@pycbouh Yeah, that seems to be the case.

Either way, I think this is a good template, so I've got no complaints. :)

**Comment by fire** [comment]
What is blocking merging this?

**Comment by Calinou** [comment]
**Update:** The feature is now generally available, which means you can preview the form on my fork: https://github.com/Calinou/godot-proposals/issues/new?assignees=&labels=&template=feature_enhancement_proposal.yml

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
