### PR TITLE
Add information on what to do if your proposal was closed as a duplicate

### PR DESCRIPTION
**Pull request by Calinou**
This is often not clear, but the recommended approach is to comment in the original proposal if your proposal tried to solve the problem differently than the linked proposal does.

See [this discussion on Reddit](https://www.reddit.com/r/godot/comments/ineur3/the_godot_ui_system_sucks/g47sbvk/).

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by Reneator** [comment]
Would it maybe make sense to add this to the proposal repository front-page?
Something like:
"If your ticket gets marked as duplicate, this only means that your idea is similar to an existing one in topic or idea. If this happens and you feel like the other proposal doesnt fully cover yours. Feel free to add your ideas/mockups to the other ticket."

I didnt know those guidelines existed until you linked me this Pull-Request.

**Comment by Calinou** [comment]
@Reneator This is now added in the README, so it's on the front page already :slightly_smiling_face:

**Comment by Reneator** [comment]
@Calinou Oh, my bad! I had a case of stupid! (thought it would appear in the guidelines not the readme)

Thanks again!

Keep it up!

**Pull request merged**
