### PR TITLE
[Research] Add toxicity detection pipeline

### PR DESCRIPTION
**Pull request by TheDutchDevil**
## Did you ever consider the addition of a toxicity detection bot to this project? 

We’re Nathan Cassee and Alexander Serebrenik (Eindhoven University of Technology, The Netherlands), Nicole Novielli (University of Bari, Italy), Christian Kastner (Carnegie Mellon University, USA), and Bogdan Vasilescu (Carnegie Mellon University, USA). And we are conducting research to understand the effectiveness of toxicity detection bots on GitHub. As part of our research we want to understand the impact of a state of the art toxicity detection bot in your project. We hope that a better knowledge and understanding of how these toxicity bots operate can be used to further improve the health of open-source projects.

To participate in this experiment we ask you to adopt a toxicity bot in godotengine/godo-proposals. You can adopt the bot by merging this pull-request. This bot will monitor issues and pull-requests for comments containing toxicity, and will post a comment if it detects toxicity. Additionally, the bot will securely store comments and edits or deletions made to those comments. This will allow us to study the frequency of toxic comments, and whether and how toxic comments are edited or deleted.

We expect that the toxicity bot reduces toxicity in issues or in pull-requests (**NB** I know that godot-proposals is not used to collaborate on code, however, I still think running the bot in the issues could be helpful). However, there might be cases where the bot responds in issues or pull-requests where there is no toxicity (a false positive) and this might distract on-topic discussions. 

## Practicalities

Your participation in this study is completely voluntary, at any point in time you can retract your project from this study. This can be done by disabling the toxicity bot, or by sending us an email. Additionally, if you don’t want us to use the results of your project in the analysis of the study, you can always email us to inform us that you want to retract your data from the study. 

The study itself will run for roughly three months, at the end of this time we will open a PR in your project to remove the toxicity bot from the project. If after the experiment you want to keep using the toxicity bot we can also provide you with a version of the toxicity bot that does not record telemetry. 

The data collected for this study will be stored securely on a private server, and the raw data will only be available to the researchers involved in this study. When we release or publicize results of the study the results will be released anonymously or in an aggregated way. Additionally, we will not list the projects that participated in this study, nor will will we release or report on any information that can be used to compare whether one project is more toxic than the other. 

This study has been approved by the Ethical Review Board of the Eindhoven University of Technology.

## Closing and Survey

If you have any questions about the bot feel free to ask them here, or mail them to n.w.cassee@tue.nl. 

If you are not interested in participating we would really appreciate it if you would let us know why you are not participating. 

Secondly, it would be really helpful if everyone involved in the project could respond to the following survey on your expectations of the bot, especially if you are not interested in adopting the bot (https://docs.google.com/forms/d/e/1FAIpQLSepvU9208dULSwG1N20ZZRi6De2WeFaIL8IPZaogbZuVMzgiQ/viewform)!

**Note**: We are not sure how best to approach projects to participate in this study, if you thought this PR was spammy, or unhelpful, please let us know so we can modify how we invite project!

### CODE REVIEW

**Comment by groud** [comment]
Sorry, we cannot accept in our CI a bot that downloads some code from another repository and run it. This is not even an option security-wise. Github has also recently had a lot of issues with people trying to merge crypto-mining into CI workflows, so there's absolutely no desire from us to take any risk on that side.

To run such an experiment, I would suggest first to run your bot on your own server, which would crawl public Github pages, not ask on random repository to modify their CI workflow to your needs.

**Comment by TheDutchDevil** [comment]
Thanks for your quick response, and I fully understand your hesitations. We've been working on this project for a few months, and seeing the solution we chose be associated with cryptomining has been quite frustrating. 

Using the public GitHub API is something we considered, however, from a development perspective it is significantly more complex and involved. For my personal interest: Would you be more open to adopting a toxicity detection bot that does not use  the CI pipeline to run?

**Comment by Faless** [comment]
> Using the public GitHub API is something we considered, however, from a development perspective it is significantly more complex and involved.

Well, one would expect security implications of this approach would be taken more seriously, and not be discarded for simplicity.
Especially by the academia.
This basically expand the attack surface on any project that adopts it, and is honestly just bad design, especially considering that most of what you describe could be done by just reading email notification from github, without even the need to "integrate" anything in projects.

**Comment by groud** [comment]
> Would you be more open to adopting a toxicity detection bot that does not use the CI pipeline to run?

Well, I can't take the decision alone, but we have very few toxicity problems here and, thanks to a high enough number of moderators, the few remaining are solved soon enough. So we never had the need for such a bot.

And well, if there's no need for it, it's hard for us to justify the time investment. As both false positive and added notification emails (from when a bot detects something or posts something) would likely cause more annoyance than benefit on our case.

That being said, nothing prevents you to crawl the comments on this repository (or the main Godot one) to detect toxic behaviors. You could still keep the results for you and analyse them without having the need for a bot in our repository popping up to say "this is toxic behavior".

**Comment by LikeLakers2** [comment]
If I might throw my opinion into the ring...

I don't actually think the way you're executing this is a good idea. Detecting toxicity (whatever "being toxic" means to the bot) is a fine idea, but I don't think it should be leaving comments whenever it detects that. Besides the potential for some comments to be false positives (which I will admit is inevitable, but still causes a discussion to be interrupted when it doesn't need to), I don't believe publicly calling out people would be a good idea.

From personal experience having been called out publicly before, I can tell you that it's not fun. Being privately called out, in a one-on-one DM, already makes me feel afraid of doing the wrong thing, but at least I don't feel like I have a mob on me.

In comparison, being *publicly* called out almost feels like a lynching. It makes you feel afraid to continue participating, because now everyone heard what you did wrong. You don't have the luxury of being able to calm down (and thus, be able to think straight) as easily, because now it feels like everyone is looking at you. Stage fright sets in. What if you say the wrong thing now, despite trying your best to avoid being "toxic" in the future? It's *scary.*

Additionally, I think the idea of being publicly called out is bad for another reason: Often times, if that person is being unintentionally toxic (and more often than not, I'd like to think that people aren't making a conscious effort to be toxic), it just makes them feel bad. Some might be able to move past it easily, while others... might have stage fright set in, just like above. Or worse.

All around, I just think calling users out in a public manner is a bad idea.

To be clear: I have no issues with my comments being processed by a bot and given a "toxicity ranking". I don't think anyone would mind that. But you have to be careful with how you expose that information, because exposing it in the wrong way can have some nasty effects.

**Comment by Duroxxigar** [comment]
> To be clear: I have no issues with my comments being processed by a bot and given a "toxicity ranking". I don't think anyone would mind that. 

Yes. I mind that.

**Comment by Xrayez** [comment]
> However, there might be cases where the bot responds in issues or pull-requests where there is no toxicity (a false positive) and this might distract on-topic discussions.

> This bot will monitor issues and pull-requests for comments containing toxicity, and will post a comment if it detects toxicity.

Isn't it important to ensure that the research does not affect discussions to avoid observer bias? Talking about [field research](https://en.wikipedia.org/wiki/Field_research):

> When humans themselves are the subject of study, **protocols must be devised to reduce the risk of observer bias** [emphasis mine] and the acquisition of too theoretical or idealized explanations of the workings of a culture.

For example, I might go toxic by the fact that my comment was marked as toxic by a bot. 👿

**Pull request closed without merging**
