### PR TITLE
Clarify the rule regarding the requirement for filling out the template

### LINKED ISSUE #1634: Make some questions optional in the proposal template
**Describe the project you are working on:**
GDScript plugins

**Describe the problem or limitation you are having in your project:**
When creating proposals, I often find myself thinking that I cannot accurately answer the last 2 questions of the template.

- _If this enhancement will not be used often, can it be worked around with a few lines of script?_
When creating a proposal, in most cases I think that this enhancement could be used often (at least for the tasks that I am going to solve with this feature)
Also I believe that my problem cannot be solved using a workaround with a few lines, or find these solutions inconvenient. 
In reality this may not be so, and perhaps there _is_ a work-round that would suit many users instead of implementing a new feature.
However, knowledge of the intricacies and work-rounds requires a lot of experience with the engine.
So I would often like to humbly skip this question.

- _Is there a reason why this should be core and not an add-on in the asset library?_
When creating a proposal, in most cases I believe that the problem cannot be solved using an addon or this would be inconvenient.
Similar to the previous question, I cannot be sure about this as I do not have enough experience in developing addons in Godot. Although I can say for example that the current gdscript plugin API is not enough to implement the features I need, but again this may be a wrong opinion.

I noticed that other participants also often demonstrate uncertainty when answering these 2 questions.
In this case, the proposal creator's answers to some clarifying questions in the comment section could be more helpful to determine the need for the feature.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Ability to _optionally_ answer questions about addons and workrouns would be more convenient.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
One could answer questions about addons and workrouns optionally, as additional information if he considers it important.
For example, a plugin developer could indicate how he tried to implement an addon that could solve the problem and why he eventually abandoned it.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not an engine feature.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Not an engine feature.

### PR DESCRIPTION
**Pull request by Xrayez**
Closes #1634.

A similar suggestion was raised a year ago with no consensus reached in #39, but the general problem still persists as seen in #1634.

This PR clarifies that a proposal is evaluated by content, not structure (I hope that proposals are not evaluated by structure), so it's perfectly fine to omit the questions if they do not apply to a proposal. That said, if a proposal misses some *vital* information as suggested in the template, it may be closed indeed, but the proposal text can be anything as long as it's elaborate/complete/self-sufficient.

At least that's the way I'd like this to be. But do note that I haven't changed anything semantically, I believe this reflects the current situation more accurately than the former wording which is a bit unwelcoming in contrast.

Also, this elaborates on what kind of proposal is seen as proper, because the "proper" word is too vague, in my opinion.

### CODE REVIEW

**Comment by Xrayez** [comment]
There was a proposal opened by reduz recently, see #2230. As you see, half of the questions are omitted completely. This tells that those questions are actually optional to fill, and are not required to be answered directly. And this is ok, as long as this PR is merged to make this legitimate.

Otherwise, we have double standards here, don't you think? 😛

**Comment by clayjohn** [comment]
I think it is important that our rules are clear. At the same time, it is also important that we use common sense when we enforce rules. This follows Godot's pragmatic approach to everything. 

Altering the rule like in this PR is confusing for users and it fails to communicate the importance of following the template. 

Also note the section outlining how to evaluate proposals. Particularly:

> The above considerations are all balanced, no one is more important than another. Core developers have discretion to weigh the factors as they see fit.

This of course, applies to consideration number 1:

> 1. Does the proposal comply with the rules?
Read the proposal and check to see that it complies with the above-stated rules. If it does not, close the proposal.

In light of these sections, perhaps a more appropriate change would be to clarify at the top of the rules that rules will be enforced pragmatically and with compassion. That may soften the harshness of the rule without taking away from it's clarity.

**Comment by Xrayez** [comment]
> This follows Godot's pragmatic approach to everything.

Pragmatic approach also means that proposals which are created by core developers themselves should be backed up by real-life projects. Again, I don't see the **"Describe the project you're working on"** question to be answered by the core developers at all, so I doubt that the development is based on pure pragmatism. I understand that there are other channels where this information is gathered, but this kind of information should also be reflected in proposal text directly.

I understand that there's no democracy here, but again, I'd just like this to reflect the current way of governing proposals.

At the very least, I'd just replace "**Rules** for submitting a proposal" to "***Guidelines*** for submitting a proposal"...

> Also note the section outlining how to evaluate proposals. Particularly:
> 
> > The above considerations are all balanced, no one is more important than another. Core developers have discretion to weigh the factors as they see fit.

I think it's just a gateway to escape all the above rules/guidelines for the core developers.

> Altering the rule like in this PR is confusing for users and it fails to communicate the importance of following the template.

What exactly is confusing? Are you sure that this would be confusing for users?

I'd say that the current set of rules and guidelines are confusing as a whole, because some parts are written in imperative/atomistic style, and some parts are written in holistic style. If there are numerous ways to interpret the same rules, I just don't see the point of writing that stuff in the first place.

**Comment by Xrayez** [comment]
> In light of these sections, perhaps a more appropriate change would be to clarify at the top of the rules that rules will be enforced pragmatically and with compassion. That may soften the harshness of the rule without taking away from it's clarity.

See #2238.

**Comment by Xrayez** [comment]
@fire I don't like this either (looking at your 👎), but I think such wording is a better alternative between bureaucratic and autocratic systems. If the system is strict, then it's difficult to find a balance between what community needs and what core developers must handle to satisfy those needs (as a project, not as an individual).

That said, it's totally fine to leave everything as-is, but as a user, I'd find it difficult to trust a system which does not enforce those rules at the current moment (by closing proposals).

But this doesn't really matter because #2069 is there to handle it all. 🙂

Feel free to close this PR and #2238 once we enable GitHub Discussions and workflow. I present many alternatives to ease the decision making for the core developers, therefore you'll likely find something that you personally disagree with. I'm looking for both approval and constructive criticism, as long as we end up with a system to be useful for both parties.

**Pull request closed without merging**
