### PR TITLE
mock-up instead of mock up

### PR DESCRIPTION
**Pull request by MintStudios**
and feature/enhancement instead of feature / enhancement

### CODE REVIEW

**Comment by girng** [comment]
https://www.linkedin.com/pulse/well-placed-hyphen-five-common-hyphenation-traps-schmalz-faia

> Compound verbs (also known as phrasal verbs) are verbs with prepositions. Examples are wipe out, goof off, mock up, and sleep in [7]. Phrasal verbs never (yes, never) get hyphens, for a simple reason: unhyphenated (or open) phrasal verbs can be easily conjugated, and hyphenated ones can’t. Mock up can be mocked up and mocking up, whereas mock-up would be mock-upped and mock-upping, which look and sound clumsy.

Seems like mock-up is correct?

**Comment by willnationsdev** [comment]
> **Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**	> **Show a mock-up screenshots/video or a flow diagram explaining how your proposal will work:**

mock up is being used as an *adjective* for the "screenshots/video". If it were a verb, then yes, you'd want to leave out the hyphen for the reasons stated above. But because it isn't a verb at all, but rather an adjective, using a hyphen connects the two terms better and conveys that they are bound together in describing their target. Also, there is a single/plural mixup present too. It should probably be:

    **Show one or more mock-up screenshots/videos or a flow diagram explaining how your proposal will work:**

**Comment by aaronfranke** [comment]
@MintStudios This PR has conflicts now that need resolving.

For removing the spaces around the slash, if this is to be done, it needs to be done here too:

> **Feature / Enhacement Proposal**
> Please fill the questions below:

**Comment by clayjohn** [comment]
Superseded by #458 which uses the alternative spelling "mockup".

**Pull request closed without merging**
